"""
Human Rights Record endpoints (BRSR Section C, Principle 5).
Prefix /human-rights-records. organization_id always from JWT.

Child routes for the three tables are generated by _register_child()
so all three get identical create/update/delete behaviour.

NOTE: no `from __future__ import annotations` in this file. The factory
passes schema classes as closure variables; with postponed evaluation
FastAPI sees the annotation as the string "create_schema", cannot
resolve it, and every child POST/PUT fails with 422.
"""
from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.orm import Session
from app.database.session import get_db
from app.api.deps import get_current_user
from app.services.human_rights_record_service import (
    HumanRightsRecordService,
    DuplicateReportingYear,
)
from app.schemas.human_rights_record import (
    HumanRightsRecordCreate,
    HumanRightsRecordUpdate,
    HumanRightsRecordResponse,
    WorkforceCoverageCreate, WorkforceCoverageUpdate, WorkforceCoverageResponse,
    RemunerationCreate, RemunerationUpdate, RemunerationResponse,
    ComplaintCreate, ComplaintUpdate, ComplaintResponse,
)

router = APIRouter(prefix="/human-rights-records", tags=["human-rights-records"])
NOT_FOUND = "Human rights record not found"


def get_service(db: Session = Depends(get_db), current_user=Depends(get_current_user)) -> HumanRightsRecordService:
    return HumanRightsRecordService(db, current_user.organization_id)


def _conflict(exc: DuplicateReportingYear) -> HTTPException:
    return HTTPException(status_code=409, detail=f"A Principle 5 record already exists for reporting year {exc.args[0]}")


@router.post("/", response_model=HumanRightsRecordResponse, status_code=201)
def create_record(payload: HumanRightsRecordCreate, service: HumanRightsRecordService = Depends(get_service)):
    try:
        return service.create_record(payload.model_dump())
    except DuplicateReportingYear as exc:
        raise _conflict(exc)


@router.get("/", response_model=list[HumanRightsRecordResponse])
def list_records(service: HumanRightsRecordService = Depends(get_service)):
    return service.list_records()


@router.get("/{record_id}", response_model=HumanRightsRecordResponse)
def get_record(record_id: int, service: HumanRightsRecordService = Depends(get_service)):
    result = service.get_record(record_id)
    if result is None:
        raise HTTPException(status_code=404, detail=NOT_FOUND)
    return result


@router.put("/{record_id}", response_model=HumanRightsRecordResponse)
def update_record(record_id: int, payload: HumanRightsRecordUpdate, service: HumanRightsRecordService = Depends(get_service)):
    try:
        result = service.update_record(record_id, payload.model_dump(exclude_unset=True))
    except DuplicateReportingYear as exc:
        raise _conflict(exc)
    if result is None:
        raise HTTPException(status_code=404, detail=NOT_FOUND)
    return result


@router.delete("/{record_id}", status_code=204)
def delete_record(record_id: int, service: HumanRightsRecordService = Depends(get_service)):
    if not service.delete_record(record_id):
        raise HTTPException(status_code=404, detail=NOT_FOUND)


def _register_child(kind: str, path: str, label: str, create_schema, update_schema, response_schema):
    """Register POST /{record_id}/<path>, PUT and DELETE /<path>/{child_id}
    for one child table. FastAPI needs concrete schema classes per route,
    which is why this is a factory rather than one path with a `kind` param."""
    child_not_found = f"{label} row not found"

    @router.post(f"/{{record_id}}/{path}", response_model=response_schema, status_code=201, name=f"create_{kind}")
    def create_child(record_id: int, payload: create_schema, service: HumanRightsRecordService = Depends(get_service)):  # type: ignore[valid-type]
        result = service.create_child(kind, record_id, payload.model_dump())
        if result is None:
            raise HTTPException(status_code=404, detail=NOT_FOUND)
        return result

    @router.put(f"/{path}/{{child_id}}", response_model=response_schema, name=f"update_{kind}")
    def update_child(child_id: int, payload: update_schema, service: HumanRightsRecordService = Depends(get_service)):  # type: ignore[valid-type]
        result = service.update_child(kind, child_id, payload.model_dump(exclude_unset=True))
        if result is None:
            raise HTTPException(status_code=404, detail=child_not_found)
        return result

    @router.delete(f"/{path}/{{child_id}}", status_code=204, name=f"delete_{kind}")
    def delete_child(child_id: int, service: HumanRightsRecordService = Depends(get_service)):
        if not service.delete_child(kind, child_id):
            raise HTTPException(status_code=404, detail=child_not_found)


_register_child("workforce", "workforce", "Workforce coverage", WorkforceCoverageCreate, WorkforceCoverageUpdate, WorkforceCoverageResponse)
_register_child("remuneration", "remuneration", "Remuneration", RemunerationCreate, RemunerationUpdate, RemunerationResponse)
_register_child("complaint", "complaints", "Complaint", ComplaintCreate, ComplaintUpdate, ComplaintResponse)
